version: '3.8'
services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${CLIENT_LISTENING_PORT}:${CLIENT_CONTAINER_PORT}"
  #   environment:
  #     - SERVER_API_URL=${SERVER_API_URL}
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/usr/src/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${NODE_LISTENING_PORT}:${NODE_CONTAINER_PORT}"
    environment:
      CONN_STRING: "mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@mongodb"
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app
  mongodb:
    image: mongo
    ports:
      - "${MONGODB_LISTENING_PORT}:${MONGODB_CONTAINER_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.stats()" ]
      timeout: 5s
      retries: 5
    volumes:
      - ~/mongodb:/data/db
