version: '3.8'
services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${CLIENT_LISTENING_PORT}:${CLIENT_CONTAINER_PORT}"
  #   environment:
  #     - SERVER_API_URL=${SERVER_API_URL}
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/usr/src/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${NODE_LISTENING_PORT}:${NODE_CONTAINER_PORT}"
      - "${MONGODB_LISTENING_PORT}:${MONGODB_CONTAINER_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
    networks:
      - mern
  mongo:
    image: mongo
    ports:
      - "${MONGODB_LISTENING_PORT}:${MONGODB_CONTAINER_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.stats()" ]
      timeout: 5s
      retries: 5
    volumes:
      - mongodbdata:/data/db
    networks:
      - mern

networks:
  mern:


volumes:
  mongodbdata:
